### ISSUE TITLE
stdout maxBuffer exceeded

### ISSUE THREAD

**Issue by vinnyp** [azure-contrib/azure-scripty#20]
I'm writing an azure script to retrieve all the blobs in a container, but I'm getting an error - "stdout maxBuffer exceeded."

It's the equivalent to this command line:

```
 azure storage blob list <container> --account-name <foo> --account-key <bar>
```

1) is that by design?
2) Is there a way to tell scripty to only retrieve certain properties? I don't need a massive JSON response with every blob property (which is what you get if you run that command with --json). A simple list is fine.

**Comment by vinnyp** [comment]
Here's the script that's failing on me. I have 252 blobs in my container.

```
 // Import the Azure storage information
 var config = require('./azure-config.json');

 // Import Azure CLI wrapper for NodeJS
 var scripty = require('azure-scripty');

  cmds = {
    "command": 'storage blob list',
    "positional": ['mycontainername'],
    "account-name": config.accountname,
    "account-key": config.accountkey
   };

  scripty.invoke(cmds, function(err, results){

if(err) {
    console.log("\nERROR:\n" + err);
}
else
    console.log(results);
 });
```

Running it give me this:

```
 $ node list-blobs.js

 ERROR:
 Error: stdout maxBuffer exceeded.
```

**Comment by glennblock** [comment]
Hi Vinny, let me look into this. Scripts just shells out to the cli and
passes the --json switch which is passing all the data back, so it had been
designed that way. I would file a bug on the cli. (
https://github.com/azure-sdk-tools-xplat).

I will take a look though. Can you send me the full error?

**Comment by vinnyp** [comment]
Searching around, it looks like what happening is that your script is using exec, and it's hitting the max buffer before it's returned to node. Using spawn should fix the issue.

See this thread: https://github.com/jedrichards/rsyncwrapper/issues/1

> "Yeah, I think exec buffers stdout and stderr before returning it to Node all in one go, whereas spawn will launch a new process and stream the output back to Node. The max buffer for exec is only 200*1024 bytes."

Does that seem to be the root cause?

**Comment by vinnyp** [comment]
Hey Glenn, just checking in. Did you get a chance to look at this?

**Comment by glennblock** [comment]
Hi Vinny

Sorry, I will look at this today. My thinking is I will plug in using spawn
in my fork and then you can test. If all is good I will merge and push to
npm.

Does that work?

**Comment by vinnyp** [comment]
Sounds great, thanks!

**Comment by glennblock** [comment]
Hi @vinnyp it looks like per the docs I don't need to actually use spawn and can still use exec. I just have to pass the buffer size explicitly. 

See here: http://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback. 

I think I am going to just make it a param on scripty and you can up the size. As the buffer uses up memory, I don't want to set it to be too large by default.

As a side note it's better also because it is a minor change. Spawn actually requires major refactoring to work because args have to be passed as an array and currently it is a string. As strings can have quotes with spaces, there' s no simply way to just split them so I'd have to overhaul everything.

Here goes....

**Comment by glennblock** [comment]
Hi @vinnyp. 

I added the fix. You can test it out by using this install command 

```
npm install https://github.com/Winodws-Azure-Contrib/azure-scripty/tarball/master
```

To override the buffer set the maxBuffer property on the module.

``` javascript
var scripty = require('azure-scripty);
scripty.maxBuffer = 9999999999;
```

I think I may go ahead and do the refactoring though and possibly even add stream support to scripty as for your scenario it would probably be helpful to just stream out the results rather than waiting for them to all buffer up. I'll try to work on this over the next few weeks.

In the meanwhile if you can test this out and it unblocks you then I'll push to npm. 

Let me know!
Glenn

**Comment by vinnyp** [comment]
Thanks for digging into this, Glenn! I had a slight problem installing it, but I figured it out (the install URL was incorrect).

Increasing the maxBuffer worked for my scenario, I can now retrieve a list of blobs with no problem :)

**Comment by glennblock** [comment]
Awesome. I will push an update to npm. Thanks for the help on working
through this.

**Comment by glennblock** [comment]
Aaaah I see the URL was wrong now doh!
